### PR TITLE
Refactor2

### PR DESCRIPTION
**Pull request by ldworkin**

### CODE REVIEW

**Comment by mizzao** [comment]
Hey - you do know that you don't have to create a pull request on GitHub to merge one branch into another, right? :D

**Comment by ldworkin** [comment]
Hahaha I figured you probably could but was too lazy to google how! I Just
saw two buttons for "pull request" and "compare". I know I can do it via
command line; is there a way to do it in the web interface too?

**Comment by mizzao** [comment]
Nope, but the command line is pretty easy. For this commit you would have just done

```
git checkout master
git merge refactor2
git push origin master
```

and it would have produced the same result. You can also 

```
git branch -d refactor2
git push origin :refactor2
```

and it would have gotten rid of the refactor2 branch locally and on the remote (GitHub).

**Comment by ldworkin** [comment]
Got it, thanks! Next time. I'm learning. (I did a rebase yesterday and was
very proud!)

**Pull request merged**
